---
- name: Install Required Packages
  become: True
  apt:
    name={{ item }} state=present update_cache=yes allow_unauthenticated=yes
  with_items:
    - openjdk-8-jdk
    - python-pip
    - virtualenv
    - git
    - ant
    - build-essential
    - devscripts
    - lintian
    - diffutils
    - patch
    - patchutils
    - dpatch
    - lvm2
    - quilt

- name: Install AWS cli
  pip: name={{ item }} state=present
  with_items:
    - awscli
    - cassandra-driver

